apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-blue-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-blue-dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/roxsross/workshop-roxs-eks-blueprints-gitops.git
    targetRevision: master
    path: teams/blue/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true